import{initializeApp,getApps}from"https://www.gstatic.com/firebasejs/10.12.2/firebase-app.js";import{getAuth,onAuthStateChanged}from"https://www.gstatic.com/firebasejs/10.12.2/firebase-auth.js";import{getFirestore,collection,addDoc,serverTimestamp,getDocs,query,where,limit}from"https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js";import{firebaseConfig}from"./platform-config.js";import{benefitMap}from"./benefit-catalog.js";
const app=getApps()[0]||initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app);let currentUser=null,currentMember=null;
const id=new URLSearchParams(location.search).get("id")||"first-health",offer=benefitMap[id]||benefitMap["first-health"],$=s=>document.querySelector(s);document.title=`${offer.title} | 전국소비자클럽`;$("#crumbTitle").textContent=offer.title;$("#detailStatus").textContent=offer.status;$("#detailCategory").textContent=offer.category;$("#detailTitle").textContent=offer.title;$("#detailLead").textContent=offer.lead;$("#detailTarget").textContent=offer.target;$("#detailArea").textContent=offer.area;$("#detailPeriod").textContent=offer.condition;$("#detailVisual").innerHTML=`<img src="${offer.image}" alt="${offer.title}">`;$("#pointGrid").innerHTML=offer.points.map((v,i)=>`<div><span>0${i+1}</span><b>${v}</b></div>`).join("");$("#stepList").innerHTML=offer.steps.map(v=>`<li>${v}</li>`).join("");$("#appType").innerHTML=offer.types.map(v=>`<option>${v}</option>`).join("");$("#formTitle").textContent=`${offer.title} 신청`;
function regionValue(value,form){const regions=[...form.elements.region.options].map(o=>o.value).filter(Boolean);return regions.find(region=>String(value||"").includes(region))||""}
async function findMember(user){let snap=await getDocs(query(collection(db,"members"),where("authUid","==",user.uid),limit(1)));if(snap.empty)snap=await getDocs(query(collection(db,"members"),where("email","==",user.email),limit(1)));return snap.empty?null:{id:snap.docs[0].id,...snap.docs[0].data()}}
function fillMember(form){if(!currentMember)return;form.elements.name.value=currentMember.name||"";form.elements.phone.value=currentMember.phone||"";form.elements.region.value=regionValue(currentMember.region,form);form.elements.name.readOnly=true;form.elements.phone.readOnly=true}
onAuthStateChanged(auth,async user=>{currentUser=user;if(!user||(!user.emailVerified&&user.email?.toLowerCase()!=="kpa100plus@gmail.com"))return;try{currentMember=await findMember(user);if(!currentMember)return;const form=$("#benefitApplicationForm");fillMember(form);$("#formMessage").textContent=`NCC 회원 ${currentMember.memberNumber||""} 정보가 자동 입력되었습니다.`}catch(e){console.error(e)}});
$("#benefitApplicationForm").addEventListener("submit",async e=>{e.preventDefault();const form=e.currentTarget,button=form.querySelector("button[type=submit]"),message=$("#formMessage"),data=Object.fromEntries(new FormData(form));if(!currentUser||!currentMember){message.innerHTML='혜택 신청은 NCC 회원 로그인 후 이용할 수 있습니다. <a href="wallet.html">NCC 회원 로그인</a>';return}const receipt=`NCC-${new Date().toISOString().slice(2,10).replaceAll("-","")}-${String(Date.now()).slice(-5)}`,record={...data,memberId:currentMember.id,memberEmail:currentUser.email,offerId:id,offerTitle:offer.title,offerTier:offer.tier,receipt,status:"new",source:"website"};button.disabled=true;button.textContent="신청 접수 중...";message.textContent="";try{await addDoc(collection(db,"benefitApplications"),{...record,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});form.hidden=true;$("#receiptNo").textContent=receipt;$("#successBox").hidden=false;$("#successBox").scrollIntoView({behavior:"smooth",block:"center"})}catch(error){console.error(error);message.textContent="신청을 접수하지 못했습니다. 로그인·회원정보·입력내용을 확인해 주세요."}finally{button.disabled=false;button.textContent="혜택 신청 접수"}});
$("#newApplication").addEventListener("click",()=>{const form=$("#benefitApplicationForm");form.reset();fillMember(form);form.hidden=false;$("#successBox").hidden=true;$("#formMessage").textContent=currentMember?`NCC 회원 ${currentMember.memberNumber||""} 정보가 자동 입력되었습니다.`:""});
