import{initializeApp,getApps}from"https://www.gstatic.com/firebasejs/10.12.2/firebase-app.js";import{getAuth,onAuthStateChanged}from"https://www.gstatic.com/firebasejs/10.12.2/firebase-auth.js";import{getFirestore,collection,addDoc,serverTimestamp,getDocs,query,where,limit}from"https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js";import{firebaseConfig}from"./platform-config.js";
const app=getApps()[0]||initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app);let currentUser=null,currentMember=null;
const makeOffer=(category,title,lead,target,area,period,image,points,steps)=>({status:"운영 테스트",category,title,lead,target,area,period,image,types:["운영 테스트 신청","모집 알림 테스트"],points,steps});
const offers={
"first-health":makeOffer("FIRST · HEALTH · 회원 우대","생활 건강관리 우대 서비스","회원과 가족이 건강상담·검진·생활관리 제휴 혜택을 이용하는 전체 흐름을 점검하는 운영 예시입니다.","NCC 소비자회원 및 가족","전국 · 지역별 제휴 예시","샘플 모집 30명 · 7일","images/card-benefit-health.webp",["건강상담·생활관리 안내 예시","지역별 제휴기관 우대조건 예시","회원 신청·선정·이용 기록 테스트"],["NCC 월렛 로그인","지역과 관심분야 확인","온라인 테스트 신청","관리자 선정·안내 확인"]),
"first-resort":makeOffer("FIRST · TRAVEL · 특별 경험","프리미엄 리조트·호텔 경험","숙박·리조트 제휴 시 회원 신청부터 선정, 예약 안내, 이용 후기까지의 운영 흐름을 확인하는 샘플입니다.","NCC 소비자회원","지역 선택 예시","샘플 모집 10팀 · 1박 예시","images/NCC_consumer.jpg",["리조트·호텔 숙박 경험 예시","선정 회원 예약 안내 흐름","이용 완료 후 후기 연결 테스트"],["희망 지역·일정 확인","온라인 테스트 신청","선정 및 예약 안내","이용 완료 기록 확인"]),
"first-culture":makeOffer("FIRST · CULTURE · 초청","문화공연·행사 초청 혜택","공연·박람회·지역행사에서 회원 초청과 좌석 선정, 안내 절차를 테스트하기 위한 운영 샘플입니다.","NCC 회원 · 동반 1인 예시","수도권 · 전국 순차 예시","샘플 20석 · 행사별 운영","images/card-channel-video.webp",["공연·박람회 초청 예시","회원 우선 신청·선정 흐름","행사 안내 및 참석 기록 테스트"],["행사 상세 확인","참석 가능 여부 확인","온라인 테스트 신청","선정 알림 및 참석 확인"]),
"premium-skincare":makeOffer("PREMIUM · BEAUTY · 무료 경험","프리미엄 스킨케어 경험단","제품 제공부터 사용 후 의견 작성까지 무료 경험 프로그램의 신청·선정·배송 흐름을 확인합니다.","NCC 소비자회원","전국배송 예시","샘플 모집 50명 · 14일","images/card-benefit-beauty.webp",["스킨케어 제품 무료 경험 예시","배송지 자동입력·선정 테스트","경험 완료 후 의견·후기 연결"],["상품·조건 확인","온라인 테스트 신청","선정 후 배송 안내","사용 후 경험 기록"]),
"premium-healthfood":makeOffer("PREMIUM · FOOD · 무료 경험","건강식품 무료 경험","건강식품의 상품 설명, 신청조건, 배송, 이용 후 의견까지 소비자 경험단 운영을 점검하는 예시입니다.","NCC 소비자회원","전국배송 예시","샘플 모집 40명 · 14일","images/NCC_business.jpg",["건강식품 제공 조건 예시","신청자 선정·배송 흐름 테스트","경험 의견 및 후기 연결"],["제품 안내 확인","온라인 테스트 신청","선정·배송 상태 확인","이용 후 의견 작성"]),
"premium-living":makeOffer("PREMIUM · LIVING · 상품 경험","생활용품 경험단","주방·청소·생활제품의 신청, 선정, 배송, 이용 기록을 점검하기 위한 회원 경험단 샘플입니다.","NCC 소비자회원","전국배송 예시","샘플 모집 60명 · 1인 1상품","images/card-channel-review.webp",["생활용품 무료 경험 예시","회원 배송지 연동 테스트","상품별 이용 의견 수집 흐름"],["관심 상품 확인","온라인 테스트 신청","선정·배송 안내 확인","이용 완료 및 후기"]),
"daily-local":makeOffer("DAILY · LOCAL · 지역 혜택","우리 동네 가맹점 회원 우대","지역 파트너 매장에서 NCC 회원 확인 후 우대 혜택을 제공하는 방문형 운영 흐름을 점검합니다.","NCC 소비자회원","전국 지역별 예시","상시 혜택 운영 예시","images/card-benefit-local.webp",["NCC 회원 대상 매장 우대 예시","지역·업종별 혜택 검색 흐름","방문 후 이용 인증·기록 테스트"],["지역 혜택 검색","매장·조건 확인","온라인 테스트 신청","방문·이용 기록 확인"]),
"daily-food":makeOffer("DAILY · FOOD · 방문형","지역 카페·음식점 회원 혜택","카페·음식점 방문형 혜택의 지역 선택, 신청, 매장 이용 안내를 확인하기 위한 운영 예시입니다.","NCC 소비자회원","지역별 운영 예시","1인 1회 · 기간 예시","images/NCC_local_store.jpg",["카페·음식점 회원 우대 예시","지역별 방문형 신청 테스트","매장 이용 후 후기 흐름"],["가까운 매장 선택","제공 혜택 확인","방문형 테스트 신청","매장 이용·후기 확인"]),
"daily-beauty":makeOffer("DAILY · BEAUTY · 생활서비스","미용·생활서비스 우대","미용실·세탁·홈케어 등 생활밀착 서비스의 예약형 신청과 이용 절차를 점검하는 예시입니다.","NCC 소비자회원","지역별 운영 예시","예약형 · 상시 예시","images/card-partner-store.webp",["미용·생활서비스 우대 예시","지역 파트너 예약 연결 테스트","회원 이용내역·후기 흐름"],["서비스·지역 선택","우대조건 확인","예약형 테스트 신청","이용 완료 확인"])
};
const id=new URLSearchParams(location.search).get("id")||"first-health",offer=offers[id]||offers["first-health"],$=s=>document.querySelector(s);document.title=`${offer.title} | 전국소비자클럽`;$("#crumbTitle").textContent=offer.title;$("#detailStatus").textContent=offer.status;$("#detailCategory").textContent=offer.category;$("#detailTitle").textContent=offer.title;$("#detailLead").textContent=offer.lead;$("#detailTarget").textContent=offer.target;$("#detailArea").textContent=offer.area;$("#detailPeriod").textContent=offer.period;$("#detailVisual").innerHTML=`<img src="${offer.image}" alt="${offer.title}">`;$("#pointGrid").innerHTML=offer.points.map((v,i)=>`<div><span>0${i+1}</span><b>${v}</b></div>`).join("");$("#stepList").innerHTML=offer.steps.map(v=>`<li>${v}</li>`).join("");$("#appType").innerHTML=offer.types.map(v=>`<option>${v}</option>`).join("");$("#formTitle").textContent=`${offer.title} 테스트 신청`;
function regionValue(value,form){const regions=[...form.elements.region.options].map(o=>o.value).filter(Boolean);return regions.find(region=>String(value||"").includes(region))||""}
async function findMember(user){let snap=await getDocs(query(collection(db,"members"),where("authUid","==",user.uid),limit(1)));if(snap.empty)snap=await getDocs(query(collection(db,"members"),where("email","==",user.email),limit(1)));return snap.empty?null:{id:snap.docs[0].id,...snap.docs[0].data()}}
function fillMember(form){if(!currentMember)return;form.elements.name.value=currentMember.name||"";form.elements.phone.value=currentMember.phone||"";form.elements.region.value=regionValue(currentMember.region,form);form.elements.name.readOnly=true;form.elements.phone.readOnly=true}
onAuthStateChanged(auth,async user=>{currentUser=user;if(!user||(!user.emailVerified&&user.email?.toLowerCase()!=="kpa100plus@gmail.com"))return;try{currentMember=await findMember(user);if(!currentMember)return;const form=$("#demoApplicationForm");fillMember(form);$("#formMessage").textContent=`NCC 회원 ${currentMember.memberNumber||""} 정보가 자동 입력되었습니다.`}catch(e){console.error(e)}});
$("#demoApplicationForm").addEventListener("submit",async e=>{e.preventDefault();const form=e.currentTarget,button=form.querySelector("button[type=submit]"),message=$("#formMessage"),data=Object.fromEntries(new FormData(form));if(!currentUser||!currentMember){message.innerHTML='테스트 신청은 NCC 회원 로그인 후 이용할 수 있습니다. <a href="wallet.html">NCC 월렛 로그인</a>';return}const receipt=`NCC-${new Date().toISOString().slice(2,10).replaceAll("-","")}-${String(Date.now()).slice(-5)}`,record={...data,memberId:currentMember.id,memberEmail:currentUser.email,offerId:id,offerTitle:`[운영 테스트] ${offer.title}`,receipt,status:"new",source:"website"};button.disabled=true;button.textContent="테스트 신청 접수 중...";message.textContent="";try{await addDoc(collection(db,"benefitApplications"),{...record,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});form.hidden=true;$("#receiptNo").textContent=receipt;$("#successBox").hidden=false;$("#successBox").scrollIntoView({behavior:"smooth",block:"center"})}catch(error){console.error(error);message.textContent="테스트 신청을 접수하지 못했습니다. 로그인·회원정보·입력내용을 확인해 주세요."}finally{button.disabled=false;button.textContent="운영 테스트 신청 접수"}});
$("#newApplication").addEventListener("click",()=>{const form=$("#demoApplicationForm");form.reset();fillMember(form);form.hidden=false;$("#successBox").hidden=true;$("#formMessage").textContent=currentMember?`NCC 회원 ${currentMember.memberNumber||""} 정보가 자동 입력되었습니다.`:""});
