import{initializeApp,getApps}from"https://www.gstatic.com/firebasejs/10.12.2/firebase-app.js";
import{getAuth,onAuthStateChanged}from"https://www.gstatic.com/firebasejs/10.12.2/firebase-auth.js";
import{getFirestore,collection,query,where,getDocs,addDoc,doc,updateDoc,setDoc,increment,serverTimestamp,limit,runTransaction}from"https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js";
import{firebaseConfig}from"./platform-config.js";
const app=getApps()[0]||initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),$=s=>document.querySelector(s),ADMIN="kpa100plus@gmail.com";
const params=new URLSearchParams(location.search),kind=document.querySelector("[data-feedback-target]")?.dataset.feedbackTarget||"benefit",targetId=params.get("id")||(kind==="benefit"?"skincare":""),targetKey=`${kind}:${targetId}`;
let user=null,member=null,eligible=null,comments=[],reviews=[];
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const mask=n=>{const s=String(n||"NCC회원");return s.length<2?`${s}*`:`${s[0]}${"*".repeat(Math.min(3,s.length-1))}`};
const date=v=>{const d=v?.toDate?.()||new Date();return new Intl.DateTimeFormat("ko-KR",{dateStyle:"medium"}).format(d)};
const forbidden=/도박|불법|사기|욕설|비방/;
async function loadMember(){if(!user)return;const snap=await getDocs(query(collection(db,"members"),where("email","==",user.email),limit(1)));if(!snap.empty)member={id:snap.docs[0].id,...snap.docs[0].data()}}
async function loadComments(){try{const snap=await getDocs(query(collection(db,"expectationComments"),where("targetKey","==",targetKey),where("status","==","visible")));comments=snap.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(b.createdAt?.seconds||0)-(a.createdAt?.seconds||0));renderComments()}catch(e){console.error(e);$("#expectationList").innerHTML='<div class="empty-state">기대평을 불러오지 못했습니다.</div>'}}
function renderComments(){const area=$("#expectationList");area.innerHTML=comments.length?comments.map(v=>`<article class="feedback-item"><div class="feedback-meta"><b>${esc(v.authorMasked)}</b><span>${date(v.createdAt)}</span></div><p>${esc(v.content)}</p><div class="feedback-actions"><button data-like="${v.id}">좋아요 ${Number(v.likeCount||0)}</button><button data-report="comment:${v.id}">신고</button></div></article>`).join(""):'<div class="empty-state">첫 기대평·응원 한마디를 남겨주세요.</div>';area.querySelectorAll("[data-like]").forEach(b=>b.onclick=like);area.querySelectorAll("[data-report]").forEach(b=>b.onclick=report)}
async function loadReviews(){try{const snap=await getDocs(query(collection(db,"reviews"),where("targetKey","==",targetKey),where("status","==","visible")));reviews=snap.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(b.createdAt?.seconds||0)-(a.createdAt?.seconds||0));renderReviews()}catch(e){console.error(e);$("#reviewList").innerHTML='<div class="empty-state">후기를 불러오지 못했습니다.</div>'}}
function renderReviews(){const area=$("#reviewList");area.innerHTML=reviews.length?reviews.map(v=>`<article class="review-item"><div class="feedback-meta"><b>${esc(v.authorMasked)} · <span class="review-stars">${"★".repeat(v.rating)}${"☆".repeat(5-v.rating)}</span></b><span>${date(v.createdAt)} · 이용 인증</span></div><h3>${esc(v.title)}</h3><p>${esc(v.content)}</p><div class="feedback-actions"><button data-report="review:${v.id}">신고</button></div></article>`).join(""):'<div class="empty-state">등록된 이용 인증 후기가 없습니다.</div>';area.querySelectorAll("[data-report]").forEach(b=>b.onclick=report)}
async function checkEligibility(){const message=$("#reviewMessage");if(!user){message.textContent="후기를 작성하려면 NCC 월렛에서 로그인해 주세요.";return}if(!member){message.textContent="연결된 NCC 회원정보를 찾을 수 없습니다.";return}try{const col=kind==="groupbuy"?"groupBuyOrders":"benefitApplications",status=kind==="groupbuy"?"completed":"approved",targetField=kind==="groupbuy"?"productId":"offerId",snap=await getDocs(query(collection(db,col),where("memberId","==",member.id),where(targetField,"==",targetId)));eligible=snap.docs.map(d=>({id:d.id,...d.data()})).find(v=>v.status===status);if(eligible){$("#reviewForm").hidden=false;message.textContent="이용 완료 기록이 확인되었습니다. 이용 인증 후기를 작성할 수 있습니다."}else message.textContent=kind==="groupbuy"?"배송·이용 완료 처리된 주문이 확인되면 후기 작성이 열립니다.":"선정·승인 완료된 신청이 확인되면 후기 작성이 열립니다."}catch(e){console.error(e);message.textContent="이용 기록을 확인하지 못했습니다. 관리자에게 문의해 주세요."}}
$("#expectationForm")?.addEventListener("submit",async e=>{e.preventDefault();const message=$("#expectationMessage"),input=$("#expectationInput"),content=input.value.trim();if(!user||!user.emailVerified){message.textContent="NCC 월렛에서 로그인과 이메일 인증을 완료해 주세요.";return}if(!member){message.textContent="연결된 NCC 회원정보가 없습니다.";return}if(content.length<2||content.length>180||forbidden.test(content)){message.textContent="2~180자의 건전한 내용으로 작성해 주세요.";return}const button=e.currentTarget.querySelector("button");button.disabled=true;try{await addDoc(collection(db,"expectationComments"),{targetType:kind,targetId,targetKey,memberId:member.id,authorEmail:user.email,authorMasked:mask(member.name),content,likeCount:0,status:"visible",createdAt:serverTimestamp(),updatedAt:serverTimestamp()});input.value="";message.textContent="기대평이 등록되었습니다.";await loadComments()}catch(err){console.error(err);message.textContent="등록하지 못했습니다. 로그인 또는 Firestore 권한을 확인해 주세요."}finally{button.disabled=false}});
$("#reviewForm")?.addEventListener("submit",async e=>{e.preventDefault();if(!eligible||!member)return;const rating=Number($("#reviewRating").value),title=$("#reviewTitle").value.trim(),content=$("#reviewContent").value.trim(),message=$("#reviewMessage");if(title.length<2||content.length<10||forbidden.test(`${title} ${content}`)){message.textContent="제목 2자 이상, 후기 10자 이상으로 작성해 주세요.";return}const button=e.currentTarget.querySelector("button");button.disabled=true;try{await setDoc(doc(db,"reviews",`${kind}_${eligible.id}`),{targetType:kind,targetId,targetKey,verificationCollection:kind==="groupbuy"?"groupBuyOrders":"benefitApplications",verificationId:eligible.id,memberId:member.id,authorEmail:user.email,authorMasked:mask(member.name),rating,title,content,verified:true,status:"visible",createdAt:serverTimestamp(),updatedAt:serverTimestamp()});e.currentTarget.reset();message.textContent="이용 인증 후기가 등록되었습니다.";await loadReviews()}catch(err){console.error(err);message.textContent="후기를 등록하지 못했습니다. 이미 작성했거나 권한이 없을 수 있습니다."}finally{button.disabled=false}});
async function like(e){if(!user){$("#expectationMessage").textContent="로그인 후 좋아요를 누를 수 있습니다.";return}const b=e.currentTarget,commentId=b.dataset.like,likeRef=doc(db,"expectationLikes",`${commentId}_${user.uid}`),commentRef=doc(db,"expectationComments",commentId);b.disabled=true;try{await runTransaction(db,async tx=>{if((await tx.get(likeRef)).exists())throw Error("already liked");tx.set(likeRef,{commentId,userId:user.uid,createdAt:serverTimestamp()});tx.update(commentRef,{likeCount:increment(1),updatedAt:serverTimestamp()})});const v=comments.find(x=>x.id===commentId);if(v)v.likeCount=Number(v.likeCount||0)+1;renderComments()}catch(err){console.error(err);$("#expectationMessage").textContent="좋아요는 한 계정에서 한 번만 누를 수 있습니다."}}
async function report(e){if(!user){alert("로그인 후 신고할 수 있습니다.");return}const[type,targetDocId]=e.currentTarget.dataset.report.split(":");const reason=prompt("신고 사유를 간단히 입력해 주세요.");if(!reason)return;try{await addDoc(collection(db,"reviewReports"),{contentType:type,targetDocId,reporterEmail:user.email,reason:reason.slice(0,300),status:"new",createdAt:serverTimestamp(),updatedAt:serverTimestamp()});alert("신고가 접수되었습니다.")}catch(err){console.error(err);alert("신고를 접수하지 못했습니다.")}}
onAuthStateChanged(auth,async u=>{user=u;if(u&&(!u.emailVerified&&u.email?.toLowerCase()!==ADMIN))user=null;try{await loadMember();await checkEligibility()}catch(e){console.error(e)}});loadComments();loadReviews();
