import{initializeApp,getApps}from"https://www.gstatic.com/firebasejs/10.12.2/firebase-app.js";
import{getAuth,onAuthStateChanged}from"https://www.gstatic.com/firebasejs/10.12.2/firebase-auth.js";
import{getFirestore,doc,getDoc,collection,addDoc,updateDoc,serverTimestamp,getDocs,query,where,limit}from"https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js";
const config={apiKey:"AIzaSyBHL7qCPUwcp9Vp_1dYWfCk2qBvRgJ9mcM",authDomain:"ncc-member.firebaseapp.com",projectId:"ncc-member",storageBucket:"ncc-member.firebasestorage.app",messagingSenderId:"772423138834",appId:"1:772423138834:web:753b6d6dc6f394904822cb"};
const app=getApps()[0]||initializeApp(config),auth=getAuth(app),db=getFirestore(app),$=s=>document.querySelector(s),id=new URLSearchParams(location.search).get("id"),ADMIN_EMAIL="kpa100plus@gmail.com";let product,member,userAddresses=[];
const money=v=>new Intl.NumberFormat("ko-KR").format(Number(v||0)),status=v=>({recruiting:"모집중",confirmed:"진행확정",closed:"마감"})[v]||"준비중";
const fillMember=d=>{const f=$("#orderForm");if(!f||!d)return;f.elements.name.value=d.name||"";f.elements.phone.value=d.phone||"";f.elements.deliveryPhone.value=d.phone||"";f.elements.recipient.value=d.name||"";f.elements.region.value=d.region||"";["name","phone","region"].forEach(k=>{if(f.elements[k].value)f.elements[k].readOnly=true});$("#orderMessage").textContent=d.memberNumber?`NCC 회원 ${d.memberNumber} 정보가 자동 입력되었습니다.`:"NCC 회원정보가 자동 입력되었습니다."};
const fillAddress=a=>{const f=$("#orderForm");f.elements.recipient.value=a?.recipient||member?.name||"";f.elements.deliveryPhone.value=a?.phone||member?.phone||"";f.elements.postalCode.value=a?.postalCode||"";f.elements.address.value=a?.address||"";f.elements.addressDetail.value=a?.addressDetail||""};
$("#orderForm").elements.agree.style.width="auto";
try{const cached=JSON.parse(sessionStorage.getItem("nccMemberProfile")||"null");if(cached)fillMember(cached)}catch{}
onAuthStateChanged(auth,async user=>{if(!user||(!user.emailVerified&&user.email?.toLowerCase()!==ADMIN_EMAIL))return;try{const snap=await getDocs(query(collection(db,"members"),where("email","==",user.email),limit(1)));if(snap.empty)return;member={id:snap.docs[0].id,...snap.docs[0].data()};sessionStorage.setItem("nccMemberProfile",JSON.stringify({id:member.id,name:member.name||"",phone:member.phone||"",region:member.region||"",email:member.email||"",memberNumber:member.memberNumber||""}));fillMember(member);await loadAddresses()}catch(e){console.error(e)}});
async function loadAddresses(){const snap=await getDocs(query(collection(db,"memberAddresses"),where("memberId","==",member.id)));userAddresses=snap.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>Number(b.isDefault)-Number(a.isDefault));const select=$("#savedAddress");select.innerHTML='<option value="new">새 배송지 작성</option>'+userAddresses.map(a=>`<option value="${a.id}">${a.isDefault?"[기본] ":""}${a.label} · ${a.address}</option>`).join("");$("#savedAddressField").hidden=false;$("#saveAddressField").hidden=false;if(userAddresses.length){select.value=userAddresses[0].id;fillAddress(userAddresses[0]);$("#saveAddressField").hidden=true}select.onchange=()=>{const a=userAddresses.find(v=>v.id===select.value);fillAddress(a);$("#saveAddressField").hidden=Boolean(a)}}
try{if(!id)throw Error("missing id");const snap=await getDoc(doc(db,"groupBuyProducts",id));if(!snap.exists())throw Error("not found");product={id:snap.id,...snap.data()};if(!product.published)throw Error("not published");$("#productImage").src=product.image||"images/NCC_consumer.jpg";$("#productImage").alt=product.title;$("#productBadge").textContent=`${product.category||"NCC 공동구매"} · ${status(product.status)}`;$("#productTitle").textContent=product.title;$("#productDescription").textContent=product.description||product.subtitle||"";$("#productPrice").textContent=`${money(product.price)}원`;$("#regularPrice").textContent=product.regularPrice?`${money(product.regularPrice)}원`:"";$("#productPeriod").textContent=`${product.startDate||"협의중"} ~ ${product.endDate||"협의중"}`;$("#productTarget").textContent=`${money(product.minParticipants)}명`;$("#productShipping").textContent=product.shipping||"모집 확정 후 안내";$("#productSupplier").textContent=product.supplier||"NCC 제휴 파트너";document.title=`${product.title} | NCC 공동구매`;$("#productLoading").hidden=true;$("#productDetail").hidden=false;if(product.status==="closed"){$("#orderButton").disabled=true;$("#orderButton").textContent="모집 마감"}}catch(e){console.error(e);$("#productLoading").textContent="확인할 수 없는 상품이거나 모집이 종료되었습니다.";$("#orderForm").hidden=true}
async function saveNewAddress(form,data){if(!member||!form.elements.saveAddress.checked)return;if(form.elements.defaultAddress.checked)await Promise.all(userAddresses.filter(a=>a.isDefault).map(a=>updateDoc(doc(db,"memberAddresses",a.id),{isDefault:false,updatedAt:serverTimestamp()})));await addDoc(collection(db,"memberAddresses"),{memberId:member.id,label:"공동구매 배송지",recipient:data.recipient.trim(),phone:data.deliveryPhone.trim(),postalCode:data.postalCode.trim(),address:data.address.trim(),addressDetail:data.addressDetail.trim(),isDefault:form.elements.defaultAddress.checked,createdAt:serverTimestamp(),updatedAt:serverTimestamp()})}
$("#orderForm").addEventListener("submit",async e=>{e.preventDefault();if(!product||product.status==="closed")return;const form=e.currentTarget,button=$("#orderButton"),message=$("#orderMessage"),data=Object.fromEntries(new FormData(form)),phoneKey=String(data.phone||"").replace(/\D/g,"");if(!member){message.innerHTML='공동구매는 NCC 회원 로그인 후 신청할 수 있습니다. <a href="wallet.html">NCC 회원 로그인</a>';return}if(phoneKey.length<9||phoneKey.length>11){message.textContent="연락처를 정확히 입력해 주세요.";return}const receipt=`NCC-G-${new Date().toISOString().slice(2,10).replaceAll("-","")}-${String(Date.now()).slice(-5)}`,quantity=Number(data.quantity),totalPrice=Number(product.price||0)*quantity,fullAddress=[data.postalCode,data.address,data.addressDetail].filter(Boolean).join(" ").slice(0,300),orderMessage=[`수령인: ${data.recipient}`,`배송연락처: ${data.deliveryPhone}`,data.message||""].filter(Boolean).join(" / ").slice(0,500);button.disabled=true;button.textContent="접수 중...";message.textContent="";try{await saveNewAddress(form,data);await addDoc(collection(db,"groupBuyOrders"),{productId:product.id,productTitle:product.title,memberId:member.id,memberEmail:member.email,name:data.name,phone:data.phone,phoneKey,quantity,region:data.region,address:fullAddress,message:orderMessage,receipt,totalPrice,status:"new",source:"website",createdAt:serverTimestamp(),updatedAt:serverTimestamp()});form.hidden=true;$("#orderResult").hidden=false;$("#orderResult").innerHTML=`<h3>참여 신청이 접수되었습니다.</h3><p>접수번호 <b>${receipt}</b></p><p>신청수량 ${quantity}개 · 예상금액 ${money(totalPrice)}원</p><p>모집 확정 후 담당자가 결제와 배송 방법을 안내합니다.</p>`}catch(error){console.error(error);message.textContent="신청을 접수하지 못했습니다. 입력 내용과 배송지 권한을 확인한 후 다시 시도해 주세요."}finally{button.disabled=false;button.textContent="참여 신청 접수"}});
