import{initializeApp,getApps}from"https://www.gstatic.com/firebasejs/10.12.2/firebase-app.js";import{getAuth,onAuthStateChanged}from"https://www.gstatic.com/firebasejs/10.12.2/firebase-auth.js";import{getFirestore,collection,query,where,limit,getDocs,doc,getDoc,setDoc,addDoc,updateDoc,deleteDoc,serverTimestamp}from"https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js";import{firebaseConfig}from"./platform-config.js";
const app=getApps()[0]||initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),$=s=>document.querySelector(s);let member=null,profile={},addresses=[];
const safe=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
onAuthStateChanged(auth,async user=>{if(!user){location.href="wallet.html?next=profile.html";return}try{const snap=await getDocs(query(collection(db,"members"),where("email","==",user.email),limit(1)));if(snap.empty)throw Error("회원정보를 찾을 수 없습니다.");member={id:snap.docs[0].id,...snap.docs[0].data()};await Promise.all([loadProfile(),loadAddresses()]);$("#profileStatus").hidden=true;$("#profileForm").hidden=false;$("#addressSection").hidden=false}catch(e){console.error(e);$("#profileStatus").textContent=e.message||"회원정보를 불러오지 못했습니다."}});
async function loadProfile(){const snap=await getDoc(doc(db,"memberProfiles",member.id));profile=snap.exists()?snap.data():{};const f=$("#profileForm"),a=profile.additional||{},s=profile.special||{},c=profile.consumer||{};f.job.value=a.job||"";f.familyComposition.value=a.familyComposition||"";f.interests.value=(a.interests||[]).join(", ");f.preferredProducts.value=a.preferredProducts||"";f.preferredServices.value=a.preferredServices||"";f.healthInterests.value=s.healthInterests||"";f.travelInterests.value=s.travelInterests||"";f.frequentPurchases.value=c.frequentPurchases||"";f.onlineMalls.value=c.onlineMalls||""}
$("#profileForm").onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,d=Object.fromEntries(new FormData(f));profile={...profile,memberId:member.id,memberNumber:member.memberNumber,email:member.email,phoneKey:member.phoneKey||String(member.phone||"").replace(/\D/g,""),profileVersion:1,additional:{...(profile.additional||{}),job:d.job.trim(),familyComposition:d.familyComposition.trim(),interests:d.interests.split(",").map(v=>v.trim()).filter(Boolean),preferredProducts:d.preferredProducts.trim(),preferredServices:d.preferredServices.trim()},special:{...(profile.special||{}),healthInterests:d.healthInterests.trim(),travelInterests:d.travelInterests.trim()},consumer:{...(profile.consumer||{}),frequentPurchases:d.frequentPurchases.trim(),onlineMalls:d.onlineMalls.trim()},updatedAt:serverTimestamp()};try{await setDoc(doc(db,"memberProfiles",member.id),profile,{merge:true});$("#profileMessage").textContent="내 정보가 저장되었습니다."}catch(err){console.error(err);$("#profileMessage").textContent="저장하지 못했습니다. 권한을 확인해 주세요."}};
async function loadAddresses(){const snap=await getDocs(query(collection(db,"memberAddresses"),where("memberId","==",member.id)));addresses=snap.docs.map(d=>({id:d.id,...d.data()}));renderAddresses()}
function renderAddresses(){const list=$("#addressList");list.innerHTML=addresses.length?addresses.sort((a,b)=>Number(b.isDefault)-Number(a.isDefault)).map(a=>`<article class="address-card"><div><h3>${safe(a.label||"배송지")}${a.isDefault?'<span class="default-chip">기본</span>':""}</h3><p>${safe(a.recipient)} · ${safe(a.phone)}</p><p>${safe(a.postalCode)} ${safe(a.address)} ${safe(a.addressDetail)}</p></div><div class="address-actions"><button class="mini-button" data-edit="${a.id}">수정</button><button class="mini-button" data-delete="${a.id}">삭제</button></div></article>`).join(""):'<div class="empty-state">저장된 배송지가 없습니다.</div>';list.querySelectorAll("[data-edit]").forEach(b=>b.onclick=()=>editAddress(b.dataset.edit));list.querySelectorAll("[data-delete]").forEach(b=>b.onclick=()=>removeAddress(b.dataset.delete))}
$("#addAddress").onclick=()=>openAddress();$("#cancelAddress").onclick=()=>{$("#addressForm").hidden=true};function openAddress(a={}){const f=$("#addressForm");f.reset();f.addressId.value=a.id||"";for(const k of["label","recipient","phone","postalCode","address","addressDetail"])f[k].value=a[k]||((k==="recipient"&&member.name)||(k==="phone"&&member.phone)||"");f.isDefault.checked=Boolean(a.isDefault)||!addresses.length;f.hidden=false;f.scrollIntoView({behavior:"smooth",block:"center"})}function editAddress(id){openAddress(addresses.find(a=>a.id===id)||{})}
$("#addressForm").onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,d=Object.fromEntries(new FormData(f)),id=d.addressId,payload={memberId:member.id,label:d.label.trim(),recipient:d.recipient.trim(),phone:d.phone.trim(),postalCode:d.postalCode.trim(),address:d.address.trim(),addressDetail:d.addressDetail.trim(),isDefault:f.isDefault.checked,updatedAt:serverTimestamp()};try{if(payload.isDefault)await Promise.all(addresses.filter(a=>a.isDefault&&a.id!==id).map(a=>updateDoc(doc(db,"memberAddresses",a.id),{isDefault:false,updatedAt:serverTimestamp()})));if(id)await updateDoc(doc(db,"memberAddresses",id),payload);else await addDoc(collection(db,"memberAddresses"),{...payload,createdAt:serverTimestamp()});f.hidden=true;await loadAddresses()}catch(err){console.error(err);$("#addressMessage").textContent="배송지를 저장하지 못했습니다. 권한을 확인해 주세요."}};
async function removeAddress(id){if(!confirm("이 배송지를 삭제하시겠습니까?"))return;try{await deleteDoc(doc(db,"memberAddresses",id));await loadAddresses()}catch(e){alert("배송지를 삭제하지 못했습니다.")}}
