import{initializeApp}from"https://www.gstatic.com/firebasejs/10.12.2/firebase-app.js";import{getAuth,onAuthStateChanged,signInWithEmailAndPassword,createUserWithEmailAndPassword,sendEmailVerification,sendPasswordResetEmail,signOut,reload}from"https://www.gstatic.com/firebasejs/10.12.2/firebase-auth.js";import{getFirestore,collection,getDocs,query,where,limit}from"https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js";
const config={apiKey:"AIzaSyBHL7qCPUwcp9Vp_1dYWfCk2qBvRgJ9mcM",authDomain:"ncc-member.firebaseapp.com",projectId:"ncc-member",storageBucket:"ncc-member.firebasestorage.app",messagingSenderId:"772423138834",appId:"1:772423138834:web:753b6d6dc6f394904822cb"},app=initializeApp(config),auth=getAuth(app),db=getFirestore(app),$=s=>document.querySelector(s);let currentUser;
onAuthStateChanged(auth,async user=>{currentUser=user;$("#walletLoading").hidden=true;$("#authArea").hidden=true;$("#verifyArea").hidden=true;$("#memberArea").hidden=true;if(!user){sessionStorage.removeItem("nccMemberProfile");$("#authArea").hidden=false;return}if(!user.emailVerified){$("#verifyEmail").textContent=user.email;$("#verifyArea").hidden=false;return}await loadMember(user)});
$("#loginForm").onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));await action(async()=>signInWithEmailAndPassword(auth,d.email.trim(),d.password),"로그인 정보를 확인해 주세요.")};
$("#signupForm").onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));await action(async()=>{const result=await createUserWithEmailAndPassword(auth,d.email.trim(),d.password);await sendEmailVerification(result.user);return result},"계정을 만들지 못했습니다. 이미 등록된 이메일이면 로그인 또는 비밀번호 재설정을 이용해 주세요.")};
$("#resetPassword").onclick=async()=>{const email=$("#loginForm").elements.email.value.trim();if(!email){$("#authMessage").textContent="로그인 이메일을 먼저 입력해 주세요.";return}await action(()=>sendPasswordResetEmail(auth,email),"비밀번호 재설정 메일을 보내지 못했습니다.","비밀번호 재설정 메일을 보냈습니다.")};
$("#resendVerification").onclick=async()=>{if(currentUser)await action(()=>sendEmailVerification(currentUser),"인증메일을 보내지 못했습니다.","인증메일을 다시 보냈습니다.","#verifyMessage")};
$("#checkVerification").onclick=async()=>{if(!currentUser)return;await reload(currentUser);if(currentUser.emailVerified)location.reload();else $("#verifyMessage").textContent="아직 인증되지 않았습니다. 이메일의 인증 링크를 먼저 눌러주세요."};
document.querySelectorAll(".logout-button").forEach(b=>b.onclick=()=>signOut(auth));
async function loadMember(user){try{const snap=await getDocs(query(collection(db,"members"),where("email","==",user.email),limit(1)));if(snap.empty){$("#memberArea").hidden=false;$("#memberArea").innerHTML='<div class="empty-state"><h2>연결할 NCC 회원정보가 없습니다.</h2><p>회원가입 때 등록한 이메일과 현재 인증한 이메일이 같은지 확인해 주세요.</p><button id="unmatchedLogout" class="text-button logout-button" type="button">다른 계정으로 로그인</button></div>';$("#unmatchedLogout").onclick=()=>signOut(auth);return}const d={id:snap.docs[0].id,...snap.docs[0].data()};sessionStorage.setItem("nccMemberProfile",JSON.stringify({id:d.id,name:d.name||"",phone:d.phone||"",region:d.region||"",email:d.email||"",memberNumber:d.memberNumber||""}));$("#memberName").textContent=d.name||"NCC 회원";$("#memberNumber").textContent=d.memberNumber||"회원번호 확인중";$("#memberRegion").textContent=d.region||"지역 미등록";$("#memberType").textContent=d.memberType==="consumer"?"소비자회원":d.memberType||"NCC 회원";$("#memberContact").textContent=`${d.phone||"연락처 미등록"} · ${d.email}`;$("#memberArea").hidden=false}catch(e){console.error(e);$("#memberArea").hidden=false;$("#memberArea").innerHTML='<div class="empty-state">회원정보를 불러오지 못했습니다. Firestore 회원 본인조회 권한을 확인해 주세요.</div>'}}
async function action(fn,errorText,successText="",target="#authMessage"){const el=$(target);el.textContent="처리 중입니다.";try{await fn();el.textContent=successText}catch(e){console.error(e);el.textContent=errorText}}
